server:
  port: 8085
project:
  manifest:
    file:
      path: classpath:/default-project.json
spring:
  application:
    name: microlink-workflow

  activiti:
    database-schema-update: true
    check-process-definitions: true
    deployment-mode: single-resource
    history-level: full
    db-history-used: true

  cloud:
    nacos:
      discovery:
        server-addr: 10.77.110.31:8848

  datasource:
    url: jdbc:postgresql://10.77.110.31:5432/activitidb?currentSchema=public&reWriteBatchedInserts=true
    username: activiti
    password: mypassword
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
